### ISSUE TITLE
Recommended way to setup Wifi after v24.04 server successful install

### ISSUE THREAD

**Issue by TheStophe** [tobhe/ubuntu-asahi#153]
What is the recommended way to setup a wifi or ethernet connection after successful install? I also ran into this issue with v22 server install. If netplan in `/etc/netplan` what is the recommended filename? Also, is there a group name to set them UP? (E.g. sudo ip link set wlp1s0f0 up)

I have a mac mini m1 with `ip a` of end0 and wlp1s0f0. 

> ip a
...
> end0: <BROADCAST, MULTICAST> MTU 1500 qdisc noop state DOWN group default qlen 1000
>link/ether 00: ....
> altname enp3s0
...
> wlp1s0f0: <BROADCAST, MULTICAST> MTU 1500 qdisc noop state DOWN group default qlen 1000
...

**Comment by tobhe** [comment]
The netplan docs have a [wifi example](https://netplan.readthedocs.io/en/stable/examples/#how-to-configure-your-computer-to-connect-to-your-home-wi-fi-network) that should almost work. On Ubuntu Server you need to use `renderer: networkd`. `renderer: NetworkManager` won't work because NetworkManager is not installed.

It should looks something like:
```
network:
  version: 2
  renderer: networkd
  wifis:
    wlp1s0f0:
      dhcp4: yes
      access-points:
        "network_ssid_name":
          password: "**********"
```
The file name doesn't matter as long as in ends in `.yaml` and is placed in `/etc/netplan/`, so `default.yaml` or `wifi.yaml` should both work.

EDIT: after creating the file you will have to run `netplan apply` to apply it.
